export const REQUEST_DELIM: string = "||";
export const REQUEST_DELIM_STR: string = ",";
export const REQUEST_PREFIX_EXTRA: string = "extra.";
export const FEATURE_NAME_METADATA: string = "CRUDX_FEATURE_NAME_METADATA";
export const ACTION_NAME_METADATA: string = "CRUDX_ACTION_NAME_METADATA";
export const OVERRIDE_METHOD_METADATA: string =
  "CRUDX_OVERRIDE_METHOD_METADATA";
export const PARSED_BODY_METADATA: string = "CRUDX_PARSED_BODY_METADATA";
export const PARSED_CRUD_REQUEST_KEY: string = "CRUDX_PARSED_CRUD_REQUEST_KEY";
export const CRUD_OPTIONS_METADATA: string = "CRUDX_CRUD_OPTIONS_METADATA";
export const CRUD_AUTH_OPTIONS_METADATA: string =
  "CRUDX_CRUD_AUTH_OPTIONS_METADATA";
