name: publish

on:
  release:
    types: [published]

permissions:
    contents: read

jobs:
  test:
    name: NPM Publish 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with: 
          fetch_depth: 0

      - name: Run Unit Tests
        uses: ./.github/workflows/unit.yml
      
      - name: Install Node
        uses: actions/setup-node@v4
        with: 
          node_version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm install
        shell: bash

      - name: Publish packages
        run: npx nx release publish
        shell: bash
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
